alphaSite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('sampleapp/', include('sampleapp.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

#.../polls/以降のurlを定義
#name="xxx"を付加しておけば、そのurlをハードコーディングを解消できる。href="/polls/{{ question.id }}/"を、href="{% url 'detail' question.id %}"
app_name = 'polls' #名前空間を指定した場合は、上記のコードを'detail'から'polls:detail'と変更する。
urlpatterns = [
    path('', views.index, name='name'), #polls/viewsのhello関数を実行
    path('<question_id>/', views.detail, name='detail'), #question_idはview.detail関数を呼び出す時の引数として渡される.
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

sampleapp/urls.py
from django.urls import path
from . import views

app_name = 'sampleapp'
urlpatterns = [
    #path('', views.MonthCalendar.as_view(), name='month'),
    #path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    #path('month_with_schedule/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    #path('month_with_schedule/<int:year>/<int:month>/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    #path('week/', views.WeekCalendar.as_view(), name='week'),
    #path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    #path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    #path('week_with_schedule/<int:year>/<int:month>/<int:day>/', views.WeekWithScheduleCalendar.as_view(),name='week_with_schedule'),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),
]
#使用しているのは、'mycalendar/'と'mycalendar/<int:year>/<int:month>/<int:day>/'だけ。

sampleapp/models.py
from django.db import models

# Create your models here.

scalendar/models.py
import datetime
from django.db import models
from django.utils import timezone

"""予定作成時のデータ用"""
class Schedule(models.Model):
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

sampleapp/views.py
import datetime
from django.shortcuts import redirect
from django.views import generic
from scalendar.forms import BS4ScheduleForm
from scalendar.views import MonthCalendarMixin, WeekCalendarMixin,WeekWithScheduleMixin


class MyCalendar(MonthCalendarMixin, WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面"""
    template_name = 'sampleapp/mycalendar.html'
    form_class = BS4ScheduleForm #scalendar/forms.pyでformの形を定義している。template内の{{ form }}に設置される。ここでpostしたデータを元に新規レコードがDBに自動で追加される?
    #{{ form.non_field_errors }}のように、多少プロパティをつけたformの作成も可能.もしかしたら、form_validの方で定義した方法でDBに格納されるかも.
    
    
    """
    
    templateに渡す値が、日付とスケジュールの対応が付けられたものになっているとよい。
    下記でそれを試している。get()の引数は式ではなく値である。
    この時点で、各日付（横軸）と時間（縦軸）とスケジュール（値）で対応づけられた配列のようなものがあるとよい。
    作成される表のマス数は7日*x(sec)分なので、一定。
    week.htmlでは、その分だけ回し、start_timeが一致するスケジュールがあるならば、そのマスで一回止まって設置するという流れ。
    
    縦:24時間*60分 = 1440 。30分毎にラインを引く。縦幅は一定。
    横：7つ。横幅は可変。
    
    年月日と分単位までの時刻が一致した場合、その予定をセル上に表示。セル内部ではなく、上辺をセルに合わせ、下辺はfloat状態にする。
    
    
    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week'] = self.get_week_calendar() #templateで{{ week }} とすれば、この値となる.
        l = self.get_week_calendar()['schedule_list']
        print(l)
        for num in range(7):
            l.remove(num)
        print(l)        
        #print(l[1].get(date='2018-11-06'))

        context['month'] = self.get_month_calendar() #get_month_calendar()でインスタンスを生成して、templateに渡している.レコードの保存はしない。する場合は以下のformで定義している.
        list1 = list()
        for num in range(288):
            if (num % 12) == 0: #1時間毎に区切り線を入れる.5分間隔なので、あんまり正確ではない。
                t = num / 12 + 1
                if t <= 13:
                    list1.append('午前' + str(int(t)-1) + '時' )
                else:
                    list1.append('午後' + str(int(t)-13) + '時' )
            else:
                list1.append(num + 1)
        context['list1'] = list1   
        
        context['time'] = ['1時','2時','3時']
        return context

    def form_valid(self, form): #上記のform_class=BS4scheduleFormがエラーなく通った時、実行される。
        month = self.kwargs.get('month') #self.kwargsはurlに含まれる引数(id?).日付選択時にurlが変更され、引数も変わる.それを利用している.
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today() #urlがデフォルトなままで、日付が含まれていない場合は、今日の日付けなので、date.today()。
        schedule = form.save(commit=False) #formで入力されたデータを入れる.
        schedule.date = date #その中のdateを選択している日付に変更.
        schedule.save() #DBに格納する.
        return redirect('sampleapp:mycalendar', year=date.year, month=date.month, day=date.day)

#これ以降は、個別に分けたカレンダーで使用していない.
"""
class MonthCalendar(MonthCalendarMixin, generic.TemplateView):
    #月間カレンダーを表示するビュー
    template_name = 'sampleapp/month.html'

    def get_context_data(self, **kwargs): #DBからデータを読み込む用
        context = super().get_context_data(**kwargs) #はじめに継承元のメソッドを呼び出す.たぶん、おまじないみたいなもの.
        context['month'] = self.get_month_calendar() #templateで{{ month }} とすれば、この値となる.
        return context


class WeekCalendar(WeekCalendarMixin, generic.TemplateView):
    #週間カレンダーを表示するビュー
    template_name = 'sampleapp/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week'] = self.get_week_calendar()
        return context


class WeekWithScheduleCalendar(WeekWithScheduleMixin, generic.TemplateView):
    #スケジュール付きの週間カレンダーを表示するビュー
    template_name = 'sampleapp/week_with_schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week'] = self.get_week_calendar()
        return context


class MonthWithScheduleCalendar(MonthWithScheduleMixin, generic.TemplateView):
    #スケジュール付きの月間カレンダーを表示するビュー
    template_name = 'sampleapp/month_with_schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['month'] = self.get_month_calendar()
        return context
"""

sampleapp/templates/sampleapp/base.html
<!doctype html>
<html lang="ja">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <title>カレンダー</title>
</head>
<body>
  <div class="container-fluid mt-3">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
          integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
          integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
          crossorigin="anonymous"></script>
  {% block extrajs %}{% endblock %}
</body>
</html>

sampleapp/templates/sampleapp/month.html
{% extends 'sampleapp/base.html' %}
{% block content %}

<a href="{% url 'sampleapp:month' month.previous.year month.previous.month %}">前月</a>
{{ month.current | date:"Y年m月" }}
<a href="{% url 'sampleapp:month' month.next.year month.next.month %}">次月</a>
<table class="table">
  <thead>
    <tr>
      {% for w in month.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week in month.days %}
      <tr>
        {% for day in week %}
          {% if month.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}
          {% if month.current.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

sampleapp/templates/sampleapp/month_with_schedule.html
{% extends 'sampleapp/base.html' %}
{% block content %}
<style>
    table {
        table-layout: fixed;
    }
    td > div {
      height: 100px;
      overflow: hidden;
      white-space: nowrap;
    }
</style>
<a href="{% url 'sampleapp:month_with_schedule' month.previous.year month.previous.month %}">前月</a>
{{ month.current | date:"Y年m月" }}
<a href="{% url 'sampleapp:month_with_schedule' month.next.year month.next.month %}">次月</a>
<table class="table">
  <thead>
    <tr>
      {% for w in month.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week in month.days %}
      <tr>
        {% for day, schedules in week %}
          {% if month.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}

          <div>
            {% if month.current.month != day.month %}
              {{ day | date:"m/d" }}
            {% else %}
              {{ day.day }}
            {% endif %}

            {% for schedule in schedules %}
                <p>{{ schedule.summary }}</p>
            {% endfor %}
          </div>
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

sampleapp/templates/sampleapp/mycalendar.html
{% extends 'sampleapp/base.html' %}
{% block content %}
<div class="row">
  <div class="col-md-3">
    {% include 'sampleapp/widgets/month.html' %}
    <hr>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
            <div class="col-sm-8">
              {{ field }}
              {{ field.errors }}
            </div>
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">送信</button>
    </form>
  </div>
  <div class="col-md-9">
    {% include 'sampleapp/widgets/week.html' %}
  </div>
</div>
{% endblock %}


{% block extrajs %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
<script>
    $(function() {
        // timedropper
        $( "#id_start_time" ).timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });
        $( "#id_end_time" ).timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });
    });
</script>
{% endblock %}

sampleapp/templates/sampleapp/week.html
{% extends 'sampleapp/base.html' %}
{% block content %}

<a href="{% url 'sampleapp:week' week.previous.year week.previous.month  week.previous.day %}">前週</a>
{{ week.first | date:"Y年m月d日" }}〜{{ week.last | date:"Y年m月d日" }}
<a href="{% url 'sampleapp:week' week.next.year week.next.month  week.next.day %}">次週</a>
<table class="table">
  <thead>
    <tr>
      {% for w in week.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
      <tr>
        {% for day in week.days %}
          {% if week.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}
          {% if week.first.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          </td>
        {% endfor %}
      </tr>
  </tbody>
</table>
{% endblock %}

sampleapp/templates/sampleapp/week_with_schedule.html
{% extends 'sampleapp/base.html' %}
{% block content %}

<a href="{% url 'sampleapp:week_with_schedule' week.previous.year week.previous.month  week.previous.day %}">前週</a>
{{ week.first | date:"Y年m月d日" }}〜{{ week.last | date:"Y年m月d日" }}
<a href="{% url 'sampleapp:week_with_schedule' week.next.year week.next.month  week.next.day %}">次週</a>
<table class="table table-bordered">
  <thead>
    <tr>
      {% for w in week.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
      <tr>
        {% for day in week.days %}
          {% if week.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}
          {% if week.first.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          </td>
        {% endfor %}
      </tr>
      <tr>
        {% for day_schedule_list in week.schedule_list %}
          <td>
            {% for s in day_schedule_list %}
                {{ s.start_time }} - {{ s.end_time }}<br>
                {{ s.summary }}<br>
                {{ s.description | linebreaks }}
            {% endfor %}
          </td>
        {% endfor %}
      </tr>
  </tbody>
</table>
{% endblock %}